# Generated by Django 4.1.7 on 2023-10-04 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaBuying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_campaign_date', models.DateField()),
                ('media_name', models.CharField(max_length=300, null=True)),
                ('media_platform', models.CharField(max_length=300, null=True)),
                ('media_product', models.CharField(max_length=300, null=True)),
                ('media_amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('media_date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaBuyingRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_approx_requests', models.IntegerField(null=True)),
                ('media_cost_per_request', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('media_total_impressions', models.IntegerField(null=True)),
                ('media_total_clicks', models.IntegerField(null=True)),
                ('media_request_date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('media_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mediabuying')),
            ],
        ),
    ]
