# Generated by Django 4.1.7 on 2023-10-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediabuying',
            name='media_amount_dollar',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
